Repository vedantmistryy/vedantmistryy.github.io, pull requests merged in 2022-10, with the labels that each got.

#8 Updated similarity of footer & header
  README.md
  Utils/footer.html
  Utils/header.html
  about.html
  brands.html
  contact.html
  customs.html
  index.html
Labels: hacktoberfest, Hacktoberfest-Accepted

#10 #6 is fixed
  Feature Cars/car.css
  Feature Cars/car1.html
  Feature Cars/script.js
Labels: hacktoberfest, Hacktoberfest-Accepted

#13 created CONTRIBUTING.md #7
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, Hacktoberfest-Accepted

#18 Enhanced the apprearance of cards in the cars section
  style.css
Labels: enhancement, Hacktoberfest-Accepted

#26 added dark-light mode to whole app
  about.css
  about.html
  brands.css
  brands.html
  contact.css
  contact.html
  customs.css
  customs.html
  index.html
Labels: enhancement, good first issue, Hacktoberfest-Accepted

#27 Theme position responsive overlapping fixed.
  style.css
Labels: enhancement, Hacktoberfest-Accepted

#29 Navlinks issue and Navbar Difference Issue Fixed
  contact.css
Labels: enhancement, good first issue, Hacktoberfest-Accepted

#33 added a glow on hover feature for the brands section for all brands
  brands.css
  brands.html
Labels: enhancement, good first issue, Hacktoberfest-Accepted

#44 Updated fonts
  customs.css
Labels: enhancement, Hacktoberfest-Accepted

#47 [Issue#46] CODE OF CONDUCT
  CODE_OF_CONDUCT.md
Labels: Hacktoberfest-Accepted

#45 [Issue:37] : Fixing dark mode for all pages
  about.css
  brands.css
  contact.css
  customs.css
Labels: Hacktoberfest-Accepted

#50 Added Scroll Up Button
  index.html
  script.js
  style.css
Labels: Hacktoberfest-Accepted

#65 Responsive Hamburger padding positioning issues fixed.
  src/css/about.css
  src/css/style.css
Labels: Hacktoberfest-Accepted
